FROM clojure
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY project.clj /usr/src/app/
RUN lein deps
COPY . /usr/src/app
RUN lein uberjar
EXPOSE 3011
CMD ["java", "-cp", "target/fitness-standalone.jar", "docker", "clojure.main", "-m", "fitness.main"]
